spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblogmx?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    #generate-ddl: true
  devtools:
    livereload:
      port: 35730
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
logging:
  level:
    root: warn
    com.nchu.blogmx: info
  file: log/blog-pro.log
server:
  port: 8190
 # servlet:
 #   context-path: /Ljn-blog

